name: KareHardSurvival
version: '1.1.0'
main: kare.kareHardSurvival.KareHardSurvival
api-version: '1.21.10'
authors: [ Kare ]
description: Makes the early game harder
softdepend: [UltimateAdvancementAPI]